version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:sa-east-1:593793055971:task-definition/task-definition-api-aws:4"
        LoadBalancerInfo:
          ContainerName: "api-aws"
          ContainerPort: 8080
