version: 0.0

os: linux

files:
  - source: /api-aws-1.0.0.jar
    destination: /tmp

hooks:
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 180
      runas: root
  Install:
    - location: scripts/install.sh
      timeout: 180
      runas: root
