version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:sa-east-1:593793055971:task/cluster-api-aws/68ae4da26a5d457a991e44462be936ee"
        LoadBalancerInfo:
          ContainerName: "api-aws"
          ContainerPort: 8080
