version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 593793055971.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Pulling the Docker image...
      - docker pull 593793055971.dkr.ecr.sa-east-1.amazonaws.com/schambeck/api-aws:latest

artifacts:
  type: zip
  files:
    - '**/*'
