version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean install

artifacts:
  files:
    - target/api-aws-1.0.0.jar
    - appspec.yml
    - scripts/start-process.sh
    - scripts/stop-process.sh
  discard-paths: yes
