version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 593793055971.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - ls -lah
      - docker images
      - docker build -t schambeck/api-aws .
      - ls -lah
      - docker images
      - docker tag schambeck/api-aws:latest 593793055971.dkr.ecr.sa-east-1.amazonaws.com/schambeck/api-aws:latest
#      - docker build -t api-aws:latest .
#      - docker tag api-aws:latest 593793055971.dkr.ecr.sa-east-1.amazonaws.com/schambeck/api-aws:latest
      - docker images
  post_build:
    commands:
      - echo Pushing the Docker image...
      - ls -lah
      - docker images
      - docker push 593793055971.dkr.ecr.sa-east-1.amazonaws.com/schambeck/api-aws:latest
      - ls -lah
      - docker images

artifacts:
  type: zip
  files:
    - '**/*'
