version: 0.2

phases:
  build:
    commands:
      - echo Pulling the Docker image...
      - docker pull public.ecr.aws/n2f0d5x3/schambeck/api-aws:latest

artifacts:
  type: zip
  files:
    - '**/*'
