name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t schambeck/api-aws . && docker tag schambeck/api-aws:latest public.ecr.aws/n2f0d5x3/schambeck/api-aws:latest && docker push public.ecr.aws/n2f0d5x3/schambeck/api-aws:latest
